name: CI

on:
  push:
  pull_request:

jobs:
  build-test-docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run tests
        run: pytest -q

      - name: Build Docker image
        run: docker build -t product-catalog-service:ci .

      - name: Log in to Docker Hub (optional)
        if: ${{ secrets.DOCKERHUB_USERNAME && secrets.DOCKERHUB_TOKEN }}
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Push image (optional)
        if: ${{ secrets.DOCKERHUB_USERNAME && secrets.DOCKERHUB_TOKEN }}
        run: |
          IMAGE="product-catalog-service:${{ github.sha }}"
          docker tag product-catalog-service:ci "${{ secrets.DOCKERHUB_USERNAME }}/$IMAGE"
          docker push "${{ secrets.DOCKERHUB_USERNAME }}/$IMAGE"
